### PR TITLE
Add Coin Wallet

### PR DESCRIPTION
**Pull request by nikashitsa**
## Description
Added Coin Wallet to the wallets list.

## Where should the reviewer start?
https://github.com/cardano-foundation/developer-portal/pull/868#issuecomment-1334935552

## Motivation and context
Coin Wallet is a non-custodial multicurrency wallet for multiple platforms with Cardano support. Works since 2015.

### CODE REVIEW

**Comment by rdlrt** [comment]
Thanks, the rest looks good to go, just a couple of questions for the check boxes:
1.  "Transparent Support" - admittedly it has been bought up before that it's not clear what it means, it is essentially an easy way to get in touch with individuals from the team wherein users can see each other's issues (not unidirectional platforms like twitter or blackbox like zendesk support).
2. Compatibility - Afair, I saw the mnemonics used were 12-word seed, thus - for an end user, they cannot be easily restored (unless that user understands how to derive private key using the mnemonics for given derivation scheme) across to another wallet easily?

**Comment by nikashitsa** [comment]
1. Didn't get what you mean. Coin Wallet has great support here support@coin.space. Average response time 1 business day. It's pretty transparent and clear.
2. There is an option to export your private keys in compatible to other wallets format.

**Comment by rdlrt** [comment]
> 1. Didn't get what you mean. Coin Wallet has great support here [support@coin.space](mailto:support@coin.space). Average response time 1 business day. It's pretty transparent and clear.
> 2. There is an option to export your private keys in compatible to other wallets format.

Apologies for delay
1. Unfortunately, E-mail based support are seldom transparent (that's true even for the bootstrap entity of Cardano's wallet : Daedalus(IO)/Yoroi(Emurgo). Keeping same scales, it would have to be a cross on that column.
2. Fair enough, while other wallets wont allow use of private keys to import , but rather mnemonics - but I think that could be debatable a feature missing for other wallets (might not help an average end user) - but OK to leave it as now.

**Comment by nikashitsa** [comment]
@rdlrt thanks for clarification. I've put cross on "Transparent Support" column.

**Review by rdlrt — APPROVED** [review]

**Pull request merged**
