### PR TITLE
Update list.md

### PR DESCRIPTION
**Pull request by hodlonaut**
Trust wallet is non-custodial supposedly

### CODE REVIEW

**Comment by HeptaSean** [comment]
Yes, it is. (Exodus also by the way, but with an incompatible and quite crazy key derivation.)

And with the caveat that I can only judge from seeing that there are keys derived from a seed phrase that I could use in some other client. Really verifying that keys are never sent to a server would be much harder (but also for the ones that we already believe to be non-custodial).

**Review by HeptaSean — APPROVED** [review]
Yes, as far as I can see, Trust wallet is non-custodial, does key derivation from the seed phrase on the user's device. See, for example: https://forum.cardano.org/t/please-help-me/109784/21

**Review by rdlrt — COMMENTED** [review]
As long as it satisfies [the condition ](https://github.com/cardano-community/support-faq/blob/95605833a0b980d2b5b4d85e4893c46a5e869e63/docs/Wallets/list.md?plain=1#L57) for table (exodus does not [or atleast did not, they ended up sharing user funds with their stake partner]), happy to get this merged

**Comment by HeptaSean** [comment]
> (exodus does not [or atleast did not, they ended up sharing user funds with their stake partner])

Off-topic, but interesting: Do you have a link to that story?

**Pull request merged**
